### ISSUE TITLE
Double Spaces

### ISSUE THREAD

**Issue by graywolf336** [danday74/sword-to-json#1]
Unless I am missing something, when there is a double space that is when the "extra" data is usually present. So, instead of replacing the double space with a single space, you could split the text into two and grab the first part as that will be the scripture and second part will be the extra. I tested it with the KJV and it worked, the Romans ends like it should instead of containing the extra.

Like I said though, I could be missing something

**Comment by graywolf336** [comment]
Thank you for creating this!

**Comment by graywolf336** [comment]
Never mind, some of the modules/bibles have double spaces in them and what I saw only applied to the KJV.

**Comment by danday74** [comment]
Thanks for the feedback, I am planning to revisit this as I want to create an npm module which uses this data for a bible API - sadly, I don't have time ATM but I am planning to take a few months out in a couple of years to make this happen. Not on the immediate horizon though. Your input much appreciated :) The Lord bless you
